applicationApiVersion: v1beta1

x-google-marketplace:
  # IMPORTANT: These IDs must match your listing ID in Marketplace.
  partnerId: semi-marketplace-public
  solutionId: weaviate-enterprise
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '0.22.1'
  publishedVersionMetadata:
    releaseTypes:
      - Feature
    recommended: false
    releaseNote: >-
      See https://github.com/semi-technologies/weaviate/releases/tag/0.22.1 for full release notes.

  managedUpdates:
    kalmSupported: false

  images:
    '':
      properties:
        weaviate.image.repo:
          type: REPO_WITHOUT_REGISTRY
        weaviate.image.registry:
          type: REGISTRY
        weaviate.image.tag:
          type: TAG
    contextionary-en:
      properties:
        weaviate.contextionary.repo:
          type: REPO_WITHOUT_REGISTRY
        weaviate.contextionary.registry:
          type: REGISTRY
        weaviate.contextionary.tag:
          type: TAG
    etcd:
      properties:
        weaviate.etcd.image.repository:
          type: REPO_WITHOUT_REGISTRY
        weaviate.etcd.image.registry:
          type: REGISTRY
        weaviate.etcd.image.tag:
          type: TAG
    esvector:
      properties:
        weaviate.elasticsearch.image:
          type: REPO_WITH_REGISTRY
        weaviate.elasticsearch.imageTag:
          type: TAG
    ubbagent:
      properties:
        weaviate.marketplace.ubbagentImage:
          type: FULL


properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  weaviate.marketplace.reportingSecretName:
    type: string
    default: dummysecret
    x-google-marketplace:
      type: REPORTING_SECRET
  contextionaryLanguage:
    type: string
    title: Contextionary Language
    description: "Weaviate comes with a pre-trained ML-model to build the vector space called the \"contextionary\". The contextionary is language-specific."
    enum:
    - 'English'

required:
- name
- namespace
- contextionaryLanguage
