applicationApiVersion: v1beta1

x-google-marketplace:
  # IMPORTANT: These IDs must match your listing ID in Marketplace.
  partnerId: semi-marketplace-public
  solutionId: weaviate-enterprise
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: '0.22.18'
  publishedVersionMetadata:
    releaseTypes:
      - Feature
    recommended: false
    releaseNote: >-
      Underlying Weaviate version is 0.22.16, possbily a different published version is due
      to GCP Marketplace restrictions of not being able to update the deploy
      scripts without increasing the version number.
      See https://github.com/semi-technologies/weaviate/releases/tag/0.22.16 for full release notes.

  managedUpdates:
    kalmSupported: false

  images:
    '':
      properties:
        weaviate.image.repo:
          type: REPO_WITHOUT_REGISTRY
        weaviate.image.registry:
          type: REGISTRY
        weaviate.image.tag:
          type: TAG
    contextionary-en:
      properties:
        weaviate.contextionary.repo:
          type: REPO_WITHOUT_REGISTRY
        weaviate.contextionary.registry:
          type: REGISTRY
        weaviate.contextionary.tag:
          type: TAG
    etcd:
      properties:
        weaviate.etcd.image.repository:
          type: REPO_WITHOUT_REGISTRY
        weaviate.etcd.image.registry:
          type: REGISTRY
        weaviate.etcd.image.tag:
          type: TAG
    esvector:
      properties:
        weaviate.elasticsearch.image:
          type: REPO_WITH_REGISTRY
        weaviate.elasticsearch.imageTag:
          type: TAG
    ubbagent:
      default: gcr.io/cloud-marketplace-tools/metering/ubbagent:latest
      properties:
        weaviate.marketplace.ubbagentImage:
          type: FULL

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  weaviate.marketplace.reportingSecretName:
    type: string
    default: dummysecret
    x-google-marketplace:
      type: REPORTING_SECRET
  weaviate.marketplace.planSelectionEnum:
    type: string
    title: Plan Selection
    description: 'Choose the Weaviate Subscription plan. Each plan comes with a different level of support.'
    enum:
      - 'Weaviate Open Source'
      - 'Weaviate Premium'
      - 'Weaviate Professional'
      - 'Weaviate Enterprise'
  contextionaryLanguage:
    type: string
    title: Contextionary Language
    description: 'Weaviate comes with a pre-trained ML-model to build the vector space called the "contextionary". The contextionary is language-specific.'
    enum:
      - 'English'

  weaviate.etcd.disasterRecovery.enabled:
    type: boolean
    title: Disaster recovery for etcd activated
    description: 'If true etcd will store backups on an nfs storage to recover if more than half of the nodes fail.'
    default: false
  weaviate.etcd.statefulset.replicaCount:
    type: integer
    title: Replica count of etcd pods
    description: 'How often is the etcd pod replicated. Max number must be less or equal to the number of nodes in the cluster.'
    default: 3

  weaviate.elasticsearch.replicas:
    type: integer
    title: Replica count of elastic pods
    description: 'How often is the elastic pod replicated.'
    default: 3

  weaviate.elasticsearch.resources.requests.cpu:
    type: string
    title: Requested CPU resources of elastic pods
    description: 'Defines how much CPU time each elastic pod is requesting initially, e.g. 400m.'
    default: "400m"
  weaviate.elasticsearch.resources.requests.memory:
    type: string
    title: Requested memory resources of elastic pods
    description: 'Defines how much memory each elastic pod is requesting initially, e.g. 8Gi'
    default: "8Gi"
  weaviate.elasticsearch.resources.limits.cpu:
    type: string
    title: Limited CPU resources of elastic pods
    description: 'Defines how much CPU time each elastic pod is limited to, e.g. 400m.'
    default: "4000m"
  weaviate.elasticsearch.resources.limits.memory:
    type: string
    title: Limited CPU memory resources of elastic pods
    description: 'Defines how much memory each elastic pod is limited to, e.g. 8Gi'
    default: "8Gi"
  weaviate.elasticsearch.esJavaOpts:
    type: string
    title: Elastic search java options
    description: 'Configurating the java options especially the heap size. It should be around 50% of the available memory. e.g. -Xmx4g -Xms4g for 8Gi of memory.'
    default: "-Xmx4g -Xms4g"
  
  weaviate.service.name:
    type: string
    title: Weaviate service name
    description: 'The name of the service created for weaviate in k8s.'
    default: "weaviate"
  weaviate.service.type:
    type: string
    title: Weaviate service type
    description: 'The type of the service created for weaviate in k8s.'
    default: "LoadBalancer"

  weaviate.custom_config_map.enabled:
    type: boolean
    title: Custom config map enabled
    description: 'If true weaviate will assume a custom config map at startup.'
    default: false
  weaviate.custom_config_map.name:
    type: string
    title: Custom config map name
    description: 'Name of the configmap that should be used for weaviate. Only has an effect if custom config map is enabled.'
    default: "custom-config"
    


required:
  - name
  - namespace
  - contextionaryLanguage
