apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "semi-marketplace-public", "product_id": "weaviate-enterprise", "partner_name": "SeMI Technologies B.V."}'
spec:
  descriptor:
    type: Weaviate
    version: "{{ .Values.Version }}"
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
    - group: batch/v1
      kind: Job
    - group: apps/v1beta1
      kind: StatefulSet
    - group: apps/v1beta1
      kind: Deployment
    - group: v1
      kind: PersistentVolumeClaim
    - group: v1
      kind: Service
  notes: |-
    ## Discover your Weaviate deployment
    
    Get the external IP of your Weaviate deployment using the following command:

    ```
    export WEAVIATE_HOST=$(kubectl get service weaviate \
      --namespace {{ .Release.Namespace }} \
      --output jsonpath={'.status.loadBalancer.ingress[0].ip'})
    ```

    ## Connect to your cluster
    
    Visit the `meta` endpoint to verify your cluster is running and configured
    correctly. It will print version information:

    ```
    curl http://$WEAVIATE_HOST/v1/meta
    ```

    ## Interact with your cluster
    
    Your cluster is live, ready and waiting to ingest your data. Visit the
    documentation to see how you can [add a schema](https://www.semi.technology/documentation/weaviate/current/add-data/define_schema.html),
    [import data objects](https://www.semi.technology/documentation/weaviate/current/add-data/add_and_modify.html) and
    [query data](https://www.semi.technology/documentation/weaviate/current/query-data/get.html).
